/**
 * This class is generated by jOOQ
 */
package coop.poc.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRecord extends org.jooq.impl.UpdatableRecordImpl<coop.poc.tables.records.MembersRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 707512867;

	/**
	 * Setter for <code>coopjooqpoc.members.member_id</code>.
	 */
	public void setMemberId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>coopjooqpoc.members.member_id</code>.
	 */
	public java.lang.Integer getMemberId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>coopjooqpoc.members.first_name</code>.
	 */
	public void setFirstName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>coopjooqpoc.members.first_name</code>.
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>coopjooqpoc.members.last_name</code>.
	 */
	public void setLastName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>coopjooqpoc.members.last_name</code>.
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>coopjooqpoc.members.postcode</code>.
	 */
	public void setPostcode(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>coopjooqpoc.members.postcode</code>.
	 */
	public java.lang.String getPostcode() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>coopjooqpoc.members.reward_points</code>.
	 */
	public void setRewardPoints(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>coopjooqpoc.members.reward_points</code>.
	 */
	public java.lang.Integer getRewardPoints() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>coopjooqpoc.members.favourite_store</code>.
	 */
	public void setFavouriteStore(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>coopjooqpoc.members.favourite_store</code>.
	 */
	public java.lang.Integer getFavouriteStore() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return coop.poc.tables.Members.MEMBERS.MEMBER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return coop.poc.tables.Members.MEMBERS.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return coop.poc.tables.Members.MEMBERS.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return coop.poc.tables.Members.MEMBERS.POSTCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return coop.poc.tables.Members.MEMBERS.REWARD_POINTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return coop.poc.tables.Members.MEMBERS.FAVOURITE_STORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getMemberId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPostcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getRewardPoints();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getFavouriteStore();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord value1(java.lang.Integer value) {
		setMemberId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord value2(java.lang.String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord value3(java.lang.String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord value4(java.lang.String value) {
		setPostcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord value5(java.lang.Integer value) {
		setRewardPoints(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord value6(java.lang.Integer value) {
		setFavouriteStore(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MembersRecord
	 */
	public MembersRecord() {
		super(coop.poc.tables.Members.MEMBERS);
	}

	/**
	 * Create a detached, initialised MembersRecord
	 */
	public MembersRecord(java.lang.Integer memberId, java.lang.String firstName, java.lang.String lastName, java.lang.String postcode, java.lang.Integer rewardPoints, java.lang.Integer favouriteStore) {
		super(coop.poc.tables.Members.MEMBERS);

		setValue(0, memberId);
		setValue(1, firstName);
		setValue(2, lastName);
		setValue(3, postcode);
		setValue(4, rewardPoints);
		setValue(5, favouriteStore);
	}
}
