/**
 * This class is generated by jOOQ
 */
package coop.poc;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Coopjooqpoc extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1369933114;

	/**
	 * The singleton instance of <code>coopjooqpoc</code>
	 */
	public static final Coopjooqpoc COOPJOOQPOC = new Coopjooqpoc();

	/**
	 * No further instances allowed
	 */
	private Coopjooqpoc() {
		super("coopjooqpoc");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			coop.poc.tables.Members.MEMBERS,
			coop.poc.tables.Stores.STORES);
	}
}
