/**
 * This class is generated by jOOQ
 */
package coop.poc;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>coopjooqpoc</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<coop.poc.tables.records.StoresRecord, java.lang.Integer> IDENTITY_STORES = Identities0.IDENTITY_STORES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<coop.poc.tables.records.MembersRecord> MEMBERS_PKEY = UniqueKeys0.MEMBERS_PKEY;
	public static final org.jooq.UniqueKey<coop.poc.tables.records.StoresRecord> STORES_PKEY = UniqueKeys0.STORES_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<coop.poc.tables.records.StoresRecord, java.lang.Integer> IDENTITY_STORES = createIdentity(coop.poc.tables.Stores.STORES, coop.poc.tables.Stores.STORES.STORE_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<coop.poc.tables.records.MembersRecord> MEMBERS_PKEY = createUniqueKey(coop.poc.tables.Members.MEMBERS, coop.poc.tables.Members.MEMBERS.MEMBER_ID);
		public static final org.jooq.UniqueKey<coop.poc.tables.records.StoresRecord> STORES_PKEY = createUniqueKey(coop.poc.tables.Stores.STORES, coop.poc.tables.Stores.STORES.STORE_ID);
	}
}
