/**
 * This class is generated by jOOQ
 */
package coop.poc;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poc extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -549757627;

	/**
	 * The singleton instance of <code>poc</code>
	 */
	public static final Poc POC = new Poc();

	/**
	 * No further instances allowed
	 */
	private Poc() {
		super("poc");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			coop.poc.Sequences.STORES_STORE_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			coop.poc.tables.Members.MEMBERS,
			coop.poc.tables.SchemaVersion.SCHEMA_VERSION,
			coop.poc.tables.Stores.STORES);
	}
}
