/**
 * This class is generated by jOOQ
 */
package coop.poc;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in coopjooqpoc
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table coopjooqpoc.members
	 */
	public static final coop.poc.tables.Members MEMBERS = coop.poc.tables.Members.MEMBERS;

	/**
	 * The table coopjooqpoc.stores
	 */
	public static final coop.poc.tables.Stores STORES = coop.poc.tables.Stores.STORES;
}
