CREATE USER cooppoc WITH PASSWORD 'pocpassword';

GRANT ALL PRIVILEGES ON DATABASE poc to cooppoc;
GRANT ALL ON ALL TABLES IN SCHEMA poc TO cooppoc;
GRANT USAGE ON SCHEMA poc TO cooppoc;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA poc to cooppoc;