/**
 * This class is generated by jOOQ
 */
package coop.poc.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Members extends org.jooq.impl.TableImpl<coop.poc.tables.records.MembersRecord> {

	private static final long serialVersionUID = -1881465667;

	/**
	 * The singleton instance of <code>coopjooqpoc.members</code>
	 */
	public static final coop.poc.tables.Members MEMBERS = new coop.poc.tables.Members();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<coop.poc.tables.records.MembersRecord> getRecordType() {
		return coop.poc.tables.records.MembersRecord.class;
	}

	/**
	 * The column <code>coopjooqpoc.members.member_id</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.MembersRecord, java.lang.Integer> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>coopjooqpoc.members.first_name</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.MembersRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>coopjooqpoc.members.last_name</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.MembersRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>coopjooqpoc.members.postcode</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.MembersRecord, java.lang.String> POSTCODE = createField("postcode", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>coopjooqpoc.members.reward_points</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.MembersRecord, java.lang.Integer> REWARD_POINTS = createField("reward_points", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>coopjooqpoc.members.favourite_store</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.MembersRecord, java.lang.Integer> FAVOURITE_STORE = createField("favourite_store", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>coopjooqpoc.members</code> table reference
	 */
	public Members() {
		this("members", null);
	}

	/**
	 * Create an aliased <code>coopjooqpoc.members</code> table reference
	 */
	public Members(java.lang.String alias) {
		this(alias, coop.poc.tables.Members.MEMBERS);
	}

	private Members(java.lang.String alias, org.jooq.Table<coop.poc.tables.records.MembersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Members(java.lang.String alias, org.jooq.Table<coop.poc.tables.records.MembersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, coop.poc.Coopjooqpoc.COOPJOOQPOC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<coop.poc.tables.records.MembersRecord> getPrimaryKey() {
		return coop.poc.Keys.MEMBERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<coop.poc.tables.records.MembersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<coop.poc.tables.records.MembersRecord>>asList(coop.poc.Keys.MEMBERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<coop.poc.tables.records.MembersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<coop.poc.tables.records.MembersRecord, ?>>asList(coop.poc.Keys.MEMBERS__MEMBERS_FAVOURITE_STORE_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public coop.poc.tables.Members as(java.lang.String alias) {
		return new coop.poc.tables.Members(alias, this);
	}

	/**
	 * Rename this table
	 */
	public coop.poc.tables.Members rename(java.lang.String name) {
		return new coop.poc.tables.Members(name, null);
	}
}
