/**
 * This class is generated by jOOQ
 */
package coop.poc.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stores extends org.jooq.impl.TableImpl<coop.poc.tables.records.StoresRecord> {

	private static final long serialVersionUID = 1037064975;

	/**
	 * The singleton instance of <code>poc.stores</code>
	 */
	public static final coop.poc.tables.Stores STORES = new coop.poc.tables.Stores();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<coop.poc.tables.records.StoresRecord> getRecordType() {
		return coop.poc.tables.records.StoresRecord.class;
	}

	/**
	 * The column <code>poc.stores.store_id</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.StoresRecord, java.lang.Integer> STORE_ID = createField("store_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>poc.stores.name</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.StoresRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(120).nullable(false), this, "");

	/**
	 * The column <code>poc.stores.postcode</code>.
	 */
	public final org.jooq.TableField<coop.poc.tables.records.StoresRecord, java.lang.String> POSTCODE = createField("postcode", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * Create a <code>poc.stores</code> table reference
	 */
	public Stores() {
		this("stores", null);
	}

	/**
	 * Create an aliased <code>poc.stores</code> table reference
	 */
	public Stores(java.lang.String alias) {
		this(alias, coop.poc.tables.Stores.STORES);
	}

	private Stores(java.lang.String alias, org.jooq.Table<coop.poc.tables.records.StoresRecord> aliased) {
		this(alias, aliased, null);
	}

	private Stores(java.lang.String alias, org.jooq.Table<coop.poc.tables.records.StoresRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, coop.poc.Poc.POC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<coop.poc.tables.records.StoresRecord, java.lang.Integer> getIdentity() {
		return coop.poc.Keys.IDENTITY_STORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<coop.poc.tables.records.StoresRecord> getPrimaryKey() {
		return coop.poc.Keys.STORES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<coop.poc.tables.records.StoresRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<coop.poc.tables.records.StoresRecord>>asList(coop.poc.Keys.STORES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public coop.poc.tables.Stores as(java.lang.String alias) {
		return new coop.poc.tables.Stores(alias, this);
	}

	/**
	 * Rename this table
	 */
	public coop.poc.tables.Stores rename(java.lang.String name) {
		return new coop.poc.tables.Stores(name, null);
	}
}
